-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS YEAR, 
    MONTH(B.SALES_DATE) AS MONTH, 
    A.GENDER AS GENDER, 
    COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A
INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER;